resources:
- name: RobiNino_npm_example_pipelines_gitResource
  type: GitRepo
  configuration:
    path: RobiNino/npm-example-pipelines
    gitProvider: github_RobiNino_npm_example_pipelines_integration
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
- name: npm_example_pipelines_pipeline_bi
  type: BuildInfo
  configuration:
    sourceArtifactory:    rt_RobiNino_npm_example_pipelines_integration
pipelines:
  - name: RobiNino_npm_example_pipelines_pipeline
    steps:
      - name: NpmBuild
        type: NpmBuild
        configuration:
          environmentVariables:
            'JFROG_CLI_BUILD_URL': $step_url
            'JFROG_BUILD_STATUS': 'PASS'
          resolverRepo: global-npm
          autoPublishBuildInfo: true
          forceXrayScan:        true
          integrations:
            - name:         rt_RobiNino_npm_example_pipelines_integration
          inputResources:
            - name:         RobiNino_npm_example_pipelines_gitResource
          outputResources:
            - name:         npm_example_pipelines_pipeline_bi
        execution:
          onFailure:
            - export JFROG_BUILD_STATUS=FAIL
            - jfrog rt bce
            - jfrog rt bp
