resources:
- name: RobiNino_npm_example_pipelines_gitResource
  type: GitRepo
  configuration:
    path: RobiNino/npm-example-pipelines
    gitProvider: github_robi
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
pipelines:
- name: RobiNino_npm_example_pipelines_pipeline
  configuration:
    runtime:
      type: image
      image:
        custom:
          name: releases-docker.jfrog.io/jfrog/jfrog-cli-full
          tag: latest
  steps:
  - name: Build
    type: Bash
    configuration:
      inputResources:
      - name: RobiNino_npm_example_pipelines_gitResource
      integrations:
      - name: robindev
    execution:
      onExecute:
      - cd $res_RobiNino_npm_example_pipelines_gitResource_resourcePath
      - export CI=true
      - export JFROG_CLI_BUILD_NAME=npm-example-pipelines-main
      - export JFROG_CLI_BUILD_NUMBER=$run_number
      - export JFROG_CLI_BUILD_URL=$step_url
      - export JFROG_BUILD_RESULTS=PASS
      - jfrog c add RobiNino_npm_example_pipelines_serverId --artifactory-url $int_robindev_url
        --user $int_robindev_user --apikey $int_robindev_apikey
        --enc-password=false
      - jfrog rt npm-config --server-id-resolve RobiNino_npm_example_pipelines_serverId
        --repo-resolve global-npm
      - jfrog rt npmi
      - jfrog rt bag
      - jfrog rt bce
      - jfrog rt bp
      onComplete:
      - update_commit_status RobiNino_npm_example_pipelines_gitResource
      onFailure:
      - export JFROG_BUILD_RESULTS=FAIL
      - jfrog rt bce
      - jfrog rt bp
