resources:
- name: RobiNino_npm_example_pipelines_gitResource
  type: GitRepo
  configuration:
    path: RobiNino/npm-example-pipelines
    gitProvider: github_robi
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
- name: RobiNino_npm_example_pipelines_biResource
  type: BuildInfo
  configuration:
    sourceArtifactory: robindev
pipelines:
- name: RobiNino_npm_example_pipelines_pipeline
  steps:
  - name: Build
    type: Bash
    configuration:
      inputResources:
        - name: RobiNino_npm_example_pipelines_gitResource
      integrations:
        - name: robindev
      outputResources:
        - name: RobiNino_npm_example_pipelines_biResource
    execution:
      onExecute:
      - jfrog -v
      - cd $res_RobiNino_npm_example_pipelines_gitResource_resourcePath
      - export CI=true
      - export JFROG_CLI_BUILD_NAME=npm-example-pipelines-main
      - export JFROG_CLI_BUILD_NUMBER=$run_number
      - export JFROG_CLI_BUILD_URL=$step_url
      - export JFROG_BUILD_RESULTS=PASS
      - jfrog rt c RobiNino_npm_example_pipelines_serverId --url $int_robindev_url
        --user $int_robindev_user --apikey $int_robindev_apikey
        --enc-password=false
      - jfrog rt npm-config --server-id-resolve RobiNino_npm_example_pipelines_serverId
        --repo-resolve global-npm
      - jfrog rt npmi
      - jfrog rt bag
      - jfrog rt bce
      onComplete:
      - update_commit_status RobiNino_npm_example_pipelines_gitResource
      onFailure:
      - export JFROG_BUILD_RESULTS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: publishBuildInfoStep
    type: PublishBuildInfo
    configuration:
      forceXrayScan: true
      inputSteps:
        - name: Build
      outputResources:
        - name: RobiNino_npm_example_pipelines_biResource
